/**
 * InMemoryPostRepository
 *
 * An explicit test double that implements the PostRepository port.
 *
 * Architecture:
 * - Implements the full interface contract defined in
 *   src/content/post.repository.ts.  It is not a mock generated by
 *   vi.mock(); it is a real class whose behaviour can be tested
 *   independently and whose correctness can be reasoned about without
 *   a mocking framework.
 * - The seeded posts are treated as the authoritative state.  Unlike a
 *   spy-based mock it does not record calls; callers that need to verify
 *   invocations should use a Spy wrapper on top of this class.
 *
 * Pagination contract:
 * - page is 1-based.  Requesting a page beyond totalPages yields an empty
 *   items array and the correct total/totalPages metadata — consistent with
 *   what a real CMS adapter would return.
 *
 * Sorting contract:
 * - All return values are sorted by publishedAt descending (newest first),
 *   matching the interface documentation.
 *
 * Filter contract:
 * - findPublished and findByCategory exclude draft === true posts.
 * - findByCategory additionally filters by an exact match on the category
 *   field; posts with a null/undefined category are always excluded.
 * - findAll returns ALL posts regardless of draft status.
 *
 * Single Responsibility: this class is only responsible for storing and
 * querying a fixed list of Post objects.  It has no knowledge of file I/O,
 * HTTP, Markdown parsing, or any other infrastructure concern.
 */

import type { Post, PostSummary, PostSlug, CategorySlug } from "@/content/post.types";
import type {
  PostRepository,
  PaginationParams,
  PaginatedResult,
} from "@/content/post.repository";
import { ALL_POSTS } from "@/test/fixtures/post.fixtures";

// ---------------------------------------------------------------------------
// Internal utilities
// ---------------------------------------------------------------------------

/** Sorts a readonly Post array by publishedAt descending (newest first). */
function sortByDateDesc(posts: readonly Post[]): readonly Post[] {
  return [...posts].sort((a, b) =>
    b.publishedAt.localeCompare(a.publishedAt),
  );
}

/** Applies page-number pagination to an array and returns a PaginatedResult. */
function paginate<T>(
  items: readonly T[],
  { page, perPage }: PaginationParams,
): PaginatedResult<T> {
  const total = items.length;
  const totalPages = Math.max(1, Math.ceil(total / perPage));
  const start = (page - 1) * perPage;
  const end = start + perPage;

  return {
    items: items.slice(start, end),
    total,
    page,
    perPage,
    totalPages,
  };
}

/** Strips the `content` field from a Post to produce a PostSummary. */
function toSummary(post: Post): PostSummary {
  const { content: _content, ...summary } = post;
  return summary;
}

// ---------------------------------------------------------------------------
// InMemoryPostRepository
// ---------------------------------------------------------------------------

export class InMemoryPostRepository implements PostRepository {
  /**
   * The underlying store.  Kept sorted by publishedAt descending at
   * construction time so that every query operates on pre-sorted data.
   */
  private readonly posts: readonly Post[];

  /**
   * Constructs the repository with an optional seed.
   *
   * @param seed - Posts to seed the repository with.
   *   Defaults to the canonical ALL_POSTS fixture set so that tests that
   *   do not require a specific dataset can construct the repository without
   *   arguments.
   *
   * @example
   * // Default fixture set
   * const repo = new InMemoryPostRepository();
   *
   * @example
   * // Custom seed for a focused test
   * const repo = new InMemoryPostRepository([
   *   buildPost({ category: "engineering", draft: false }),
   * ]);
   */
  constructor(seed: readonly Post[] = ALL_POSTS) {
    this.posts = sortByDateDesc(seed);
  }

  // -------------------------------------------------------------------------
  // PostRepository implementation
  // -------------------------------------------------------------------------

  /**
   * Returns every post regardless of draft status, sorted newest-first.
   */
  async findAll(): Promise<readonly Post[]> {
    return this.posts;
  }

  /**
   * Returns the post matching the given slug, or null if not found.
   * Draft status is intentionally NOT filtered here — tooling and preview
   * environments must be able to retrieve drafts by slug.
   */
  async findBySlug(slug: PostSlug): Promise<Post | null> {
    return this.posts.find((p) => p.slug === slug) ?? null;
  }

  /**
   * Returns a paginated page of published PostSummary objects filtered by
   * category.  Posts with draft === true or a null/undefined category are
   * always excluded.
   */
  async findByCategory(
    category: CategorySlug,
    pagination: PaginationParams,
  ): Promise<PaginatedResult<PostSummary>> {
    const matching = this.posts
      .filter((p) => !p.draft && p.category === category)
      .map(toSummary);

    return paginate(matching, pagination);
  }

  /**
   * Returns a paginated page of published PostSummary objects across all
   * categories.  Posts with draft === true are excluded.
   */
  async findPublished(
    pagination: PaginationParams,
  ): Promise<PaginatedResult<PostSummary>> {
    const published = this.posts.filter((p) => !p.draft).map(toSummary);

    return paginate(published, pagination);
  }
}
